### ISSUE TITLE
increasing nBands

### ISSUE THREAD

**Issue by fnzhan** [chalmersgit/SphericalHarmonics#3]
Hi, @chalmersgit   I increase the number of nBands to 10,  and check the reconstructed light image and render image. The light image becomes more accurate, while the  render image has little change as shown below.
![image](https://user-images.githubusercontent.com/21986728/71361043-b6e15c00-25cc-11ea-831c-0fc49198c13f.png)

**Comment by fnzhan** [comment]
what do you think of it? @chalmersgit

**Comment by fnzhan** [comment]
when nBands = 5, the result is below:
![image](https://user-images.githubusercontent.com/21986728/71361125-fa3bca80-25cc-11ea-9a48-4a1942d0b71d.png)

**Comment by chalmersgit** [comment]
Hi. The render function is rendering for a diffuse material. It has been shown that the first 4 bands (n=3) is able to reconstruct 99% of the diffuse surface. You'll see big differences for n=0, 1 and 3 (2 will not make a difference due to zeroed out coefficients), then not so much difference when n goes above 3.

You can check this by using my ground truth render function "getDiffuseMap(...)". This will show you what the diffuse map looks like. I bet this will look very similar to the spherical harmonic rendered ones you have shown. Let me know how it goes.

**Comment by fnzhan** [comment]
Thanks for your answer!@chalmersgit . I checked it and the ground truth is similar to render image.  But how can I reconstruct a more accurate image with a increasing nBands as shown below:
![image](https://user-images.githubusercontent.com/21986728/71390371-0e1e1580-263b-11ea-8e7d-de86506f04ad.png)
some paper said a low-pass filter is needed, and how can I do it using this repository?

**Comment by chalmersgit** [comment]
A low pass filter is done in the frequency domain by smoothing out the higher frequency coefficients (this can be done by windowing). I have two ways of supporting this. The main one is "applyWindowing(...)". The second is the "filterAmount" variable (which just blurs the input image before calculating the coefficients). Alternatively you can do your own weighted falloff on the coefficients.

Then use the coefficients to reconstruct the radiance map.

This is basically a way of reconstructing the light with less ringing artifacts. 

Let me know how it goes.

**Comment by fnzhan** [comment]
@chalmersgit  thanks for your help! it works by using the applyWindowing.

**Comment by chalmersgit** [comment]
Great to hear! Let me know if you have any other questions. Happy to help. Closing this issue now.
