### ISSUE TITLE
Image recovery using spherical harmonics

### ISSUE THREAD

**Issue by bzxgcs** [chalmersgit/SphericalHarmonics#6]
Hi, I am a novice to image processing and am working with equirectangular hdr images using your script. I have a question: for two-dimensional images, the Fourier transform can decompose and recover the image efficiently. Do spherical harmonics have similar abilities? 
For my test graph, I did 150 steps of decomposition, but the restored graph had a lot of messy ripples. If I set a larger order, the function will report an error.  I would be very grateful for your explanation. My test case has been uploaded.
file：
[output.zip](https://github.com/chalmersgit/SphericalHarmonics/files/15075074/output.zip)
raw：
![industrial_workshop_foundry_2k](https://github.com/chalmersgit/SphericalHarmonics/assets/30077906/01b1d757-aa2a-49e8-8ded-b1876b8bb559)
_sh_light_l150_SPH.exr：
![image](https://github.com/chalmersgit/SphericalHarmonics/assets/30077906/3114d8f0-0795-4f0f-b6be-9d3e6a4ea4a5)

**Comment by chalmersgit** [comment]
Hi! The problem you're encountering is called "ringing" or Gibbs phenomenon, which is a common problem in signal processing. See the wiki for an overview: https://en.m.wikipedia.org/wiki/Ringing_artifacts

The general idea is that it can be difficult to reconstruct sharp edges in an image using basis functions. The spherical harmonics are particularly not great for recovering high frequency details (made even harder in HDR images). It's typically used in games to represent low frequency lighting instead (e.g., Lambertian reflectance using 4 bands). See Figure 3 from: https://cseweb.ucsd.edu/~ravir/papers/invlamb/index.html

A common way to mitigate this issue is by filtering the image, i.e. blurring the image, thus reducing the sharp edges. We can do this in the frequency domain (see convolution theorem) using a windowing function to taper out the coefficients to 0 towards higher frequencies until a specified cut off. There are various ways to construct a windowing function, which I've provided one in my code. Feel free to try "applyWindowing(...)", or alternatively adjust the "filterAmount" variable (which just blurs the input image before calculating the coefficients).

Refer to "Deringing Spherical Harmonics" (2017) by Sloan that can solve for a windowing function.

Another basis function you may be interested in are Haar wavelets, which are able to reconstruct higher frequencies in the source image better than spherical harmonics. Please refer to the paper "All-Frequency Shadows Using Non-linear Wavelet Lighting Approximation" (2003) by Ng et al. for those details. When I implemented this method, I believe it took a few hundred coefficients to have a decent recovery of the input.

Hope that helps.

**Comment by bzxgcs** [comment]
> Hi! The problem your encountering is called "ringing" or Gibbs phenomenon, which is a common problem in signal processing. See the wiki for an overview: https://en.m.wikipedia.org/wiki/Ringing_artifacts
> 
> The general idea is that it can be difficult to reconstruct sharp edges in an image using basis functions. The spherical harmonics are particularly not great for recovering high frequency details (made even harder in HDR images). It's typically used in games to represent low frequency lighting instead (e.g., Lambertian reflectance using 4 bands). See Figure 3 from: https://cseweb.ucsd.edu/~ravir/papers/invlamb/index.html
> 
> A common way to mitigate this issue is by filtering the image, i.e. blurring the image, thus reducing the sharp edges. We can do this in the frequency domain (see convolution theorem) using a windowing function to taper out the coefficients to 0 towards higher frequencies until a specified cut off. There are various ways to construct a windowing function, which I've provided one in my code. Feel free to try "applyWindowing(...)", or alternatively adjust the "filterAmount" variable (which just blurs the input image before calculating the coefficients).
> 
> Refer to "Deringing Spherical Harmonics" (2017) by Sloan that can solve for a windowing function.
> 
> Another basis function you may be interested in are Haar wavelets, which are able to reconstruct higher frequencies in the source image better than spherical harmonics. Please refer to the paper "All-Frequency Shadows Using Non-linear Wavelet Lighting Approximation" (2003) by Ng et al. for those details. When I implemented this method, I believe it took a few hundred coefficients to have a decent recovery of the input.
> 
> Hope that helps.

Thank you, I will have a try at first.
